org.yny.sample:
  gemfire:
    locator:
      host: localhost
      port: 10334
    dataModelPackage: org.yny.sample.model.*

server:
  port: 8088

spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
